name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64  # Change JAVA_HOME to JDK 17 path
      ANDROID_SDK_ROOT: $HOME/android-sdk
      ANDROID_HOME: $HOME/android-sdk
      PATH: $HOME/android-sdk/platform-tools:$HOME/android-sdk/tools:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17  # Update this step to use JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'  # Change from 11 to 17

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34  # Ensure this matches your target SDK
          build-tools: 34.0.0  # Update this to the appropriate build tools version
          components: "platform-tools,platforms;android-34,build-tools;34.0.0"

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: List Android SDK Directory
        run: ls -R $HOME/android-sdk

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

